### ISSUE TITLE
Set up repo

### ISSUE THREAD

**Issue by jokosanyang** [jokosanyang/bookclub#9]
- Decide on tech stack
- Plan architecture

**Comment by jokosanyang** [comment]
Tech stack:
- React
- Nextjs
- Vercel for deployments
- Database - postgreSQL
- Books api - Open Library, Google Books as a backup

**Comment by jokosanyang** [comment]
Proposed site structure with URLs:
![image](https://github.com/jokosanyang/bookclub/assets/43584074/61045b80-b7e3-4570-b434-b8cc18ae3f9d)

@tloth Thoughts?

**Comment by tloth** [comment]
Lovely!
I prefer the first one: `book/[id]/meeting`
How long and complicated are these ids going to be? It would be nice to have them humanly readable/rememberable/copyable

**Comment by jokosanyang** [comment]
We could do simple incrementing numbers, the first book club book being 1, the next one 2 etc?

**Comment by tloth** [comment]
Will that not be an issue later once we have several hundreds and thousands of books?
if we want to order them, maybe
Or will it just make everything easier 😏 
If you're happy with the simple incrementing numbers, I'm happy
